version: "3"

services:
  pact-broker:
    image: pactfoundation/pact-broker:2.87.0.2
    ports:
      - "9292:9292"
    depends_on:
      - postgres
    environment:
      PACT_BROKER_BASIC_AUTH_ENABLED: 'true'
      PACT_BROKER_BASIC_AUTH_USERNAME: ${ADMIN_USER}
      PACT_BROKER_BASIC_AUTH_PASSWORD: ${ADMIN_PASSWORD}
      PACT_BROKER_BASE_URL: 'http://localhost:9292'
      PACT_BROKER_DATABASE_URL: "postgres://postgres:password@postgres/postgres"
      PACT_BROKER_LOG_LEVEL: INFO
      PACT_BROKER_SQL_LOG_LEVEL: DEBUG
      PACT_BROKER_DATABASE_CONNECT_MAX_RETRIES: "5"
  postgres:
    image: postgres
    ports:
      - "5434:5432"
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
